In [1]:
import numpy as np

In [2]:
sample_list = [10,20,30,40]

In [7]:
np.array(sample_list)

array([10, 20, 30, 40])

In [8]:
data = np.array(sample_list)

In [10]:
print(data.max())

40


In [12]:
np.ones(4) # for matrices

array([1., 1., 1., 1.])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.random.random(5)

array([0.05268806, 0.83797043, 0.00496596, 0.86618388, 0.57867118])

In [29]:
# ARRAY ARITHMETIC

In [30]:
my_list1 = [1,2]

In [31]:
my_list2 = [2,3]

In [32]:
my_list1 + my_list2

[1, 2, 2, 3]

In [33]:
numpy_array1 = np.array(my_list1)

In [34]:
numpy_array2 = np.array(my_list2)

In [35]:
numpy_array1 + numpy_array2

array([3, 5])

In [36]:
numpy_array1 * numpy_array2

array([2, 6])

In [37]:
any_array = np.array([1,2,3,4,5])

In [40]:
print(any_array.sum())

15


In [44]:
# BROADCASTING RULES
# 1. dimensions must be equal
# 2. or one of them is 1

In [45]:
# arange & indexing

In [48]:
list(range(0,10)) # in python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print(np_array[-1]) # last element

9


In [54]:
np_array[::-1] # slicing

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [56]:
np_array[2:7:]

array([2, 3, 4, 5, 6])

In [57]:
np.random.randint(1,100,5) # generates five random integers within the range of 1 to 100. 

array([19, 15, 39, 47, 16])