In [2]:
import numpy as np

In [3]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
sample_matrix1 = np.array([[1,2],[3,4]])

In [15]:
sample_matrix2 = np.array([[5,2],[6,7]])

In [18]:
sample_matrix1 + sample_matrix2

array([[ 6,  4],
       [ 9, 11]])

In [19]:
result = sample_matrix1 * 4

In [20]:
result

array([[ 4,  8],
       [12, 16]])

In [22]:
outlier_sample = np.array([1,2,3,4,5])

In [23]:
outlier_sample.shape

(5,)

In [24]:
sample_matrix1.shape

(2, 2)

In [27]:
# outlier_sample + sample_matrix1 -> ValueError: operands could not be broadcast together with shapes (5,) (2,2) 

In [28]:
# MATRIX MULTIPLICATION

In [38]:
new_matrix1 = np.array([[4,5,6]])

In [39]:
new_matrix2 = np.array([[10,20],[30,40],[50,60]])

In [40]:
new_matrix1.shape

(1, 3)

In [41]:
new_matrix2.shape

(3, 2)

In [43]:
new_matrix1

array([[4, 5, 6]])

In [44]:
new_matrix2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [46]:
new_matrix1.dot(new_matrix2) # result must be (1,2) shape matrix

array([[490, 640]])