In [1]:
import numpy as np

In [4]:
sample_matrix = np.random.randint(1,100,10)

In [5]:
sample_matrix

array([ 4, 59, 59, 65,  8,  2, 11, 20, 43, 83])

In [8]:
sample_matrix > 20 # it gives an boolean array

array([False,  True,  True,  True, False, False, False, False,  True,
        True])

In [9]:
sample_matrix[sample_matrix < 30]

array([ 4,  8,  2, 11, 20])

In [10]:
matrix_array = np.array([[2,3],[4,5],[6,7]])

In [11]:
matrix_array

array([[2, 3],
       [4, 5],
       [6, 7]])

In [12]:
matrix_array.transpose()

array([[2, 4, 6],
       [3, 5, 7]])

In [15]:
matrix_array.T # same thing

array([[2, 4, 6],
       [3, 5, 7]])

In [20]:
random_array = np.random.random((6,1)) # enclosing the input in double parentheses is obligatory

In [22]:
random_array

array([[0.56435928],
       [0.48470551],
       [0.37154436],
       [0.46104334],
       [0.10119565],
       [0.19237853]])

In [23]:
random_array.reshape((2,3))

array([[0.56435928, 0.48470551, 0.37154436],
       [0.46104334, 0.10119565, 0.19237853]])

### For potential questions

In [24]:
# Z-Score

In [26]:
data = np.array([10,12,13,15,21,100,104])

In [28]:
# standard deviation is typically consistent with the mean,
# the presence of outliers (100, 104) significantly skews the results.

In [31]:
mean = np.mean(data)
print(mean)

39.285714285714285


In [33]:
print(data.sum() / len(data))

39.285714285714285


In [35]:
std = np.std(data)
print(std)

39.80565030141283


In [36]:
# z scores

In [39]:
z_score = (data - mean) / std
z_score

array([-0.73571752, -0.6854734 , -0.66035133, -0.61010721, -0.45937484,
        1.52526803,  1.62575627])

In [40]:
# outliers

z_score[z_score > 1]

array([1.52526803, 1.62575627])

In [41]:
data[z_score > 1]

array([100, 104])

In [43]:
# LINEAR ALGEBRA <3333333

In [44]:
# 2x + 3y = 8 and 5x + 7y = 19

In [45]:
#coefficients matrix

In [48]:
A = np.array([[2,3],[5,7]])

In [49]:
# constants

In [50]:
B = np.array([8,19])

In [51]:
solution = np.linalg.solve(A,B)

In [53]:
print(solution) # x=1 and y=2

[1. 2.]
